/**
 * Calendar Export Utility
 * Generates .ics files for importing study schedules into calendar apps
 */

interface CalendarEvent {
  date: Date
  topic: string
  durationMinutes: number
  priority?: string
}

/**
 * Format date to iCal format: YYYYMMDDTHHMMSSZ
 */
function formatICalDate(date: Date): string {
  const year = date.getUTCFullYear()
  const month = String(date.getUTCMonth() + 1).padStart(2, '0')
  const day = String(date.getUTCDate()).padStart(2, '0')
  const hours = String(date.getUTCHours()).padStart(2, '0')
  const minutes = String(date.getUTCMinutes()).padStart(2, '0')
  const seconds = String(date.getUTCSeconds()).padStart(2, '0')
  
  return `${year}${month}${day}T${hours}${minutes}${seconds}Z`
}

/**
 * Generate a unique identifier for calendar events
 */
function generateUID(): string {
  return `${Date.now()}-${Math.random().toString(36).substring(2, 9)}@srep-studymate.app`
}

/**
 * Escape special characters in iCal text
 */
function escapeICalText(text: string): string {
  return text
    .replace(/\\/g, '\\\\')
    .replace(/;/g, '\\;')
    .replace(/,/g, '\\,')
    .replace(/\n/g, '\\n')
}

/**
 * Generate iCal content for a single event
 */
function generateEvent(event: CalendarEvent, index: number): string {
  const startDate = new Date(event.date)
  const endDate = new Date(startDate.getTime() + event.durationMinutes * 60 * 1000)
  
  const priorityEmoji = {
    high: '🔴',
    medium: '🟡',
    low: '🟢',
  }[event.priority || 'medium'] || '📚'

  const summary = escapeICalText(`${priorityEmoji} Study: ${event.topic}`)
  const description = escapeICalText(
    `Study session for ${event.topic}\\n` +
    `Duration: ${event.durationMinutes} minutes\\n` +
    `Priority: ${event.priority || 'medium'}\\n\\n` +
    `Generated by SREP StudyMate`
  )

  return [
    'BEGIN:VEVENT',
    `UID:${generateUID()}`,
    `DTSTAMP:${formatICalDate(new Date())}`,
    `DTSTART:${formatICalDate(startDate)}`,
    `DTEND:${formatICalDate(endDate)}`,
    `SUMMARY:${summary}`,
    `DESCRIPTION:${description}`,
    `LOCATION:Study Area`,
    `STATUS:CONFIRMED`,
    `SEQUENCE:0`,
    `PRIORITY:${event.priority === 'high' ? '1' : event.priority === 'medium' ? '5' : '9'}`,
    'BEGIN:VALARM',
    'TRIGGER:-PT15M',
    'DESCRIPTION:Study session reminder',
    'ACTION:DISPLAY',
    'END:VALARM',
    'END:VEVENT',
  ].join('\r\n')
}

/**
 * Generate complete iCal file content
 */
export function generateICalContent(
  events: CalendarEvent[],
  title: string = 'SREP Study Schedule'
): string {
  const calendarEvents = events.map((event, index) => generateEvent(event, index))

  const icalContent = [
    'BEGIN:VCALENDAR',
    'VERSION:2.0',
    'PRODID:-//SREP StudyMate//Study Schedule//EN',
    'CALSCALE:GREGORIAN',
    'METHOD:PUBLISH',
    `X-WR-CALNAME:${escapeICalText(title)}`,
    'X-WR-TIMEZONE:UTC',
    'X-WR-CALDESC:AI-generated study schedule from SREP StudyMate',
    ...calendarEvents,
    'END:VCALENDAR',
  ].join('\r\n')

  return icalContent
}

/**
 * Download iCal file in browser
 */
export function downloadICalFile(
  events: CalendarEvent[],
  title: string = 'SREP Study Schedule',
  filename: string = 'study-schedule.ics'
): void {
  const icalContent = generateICalContent(events, title)
  const blob = new Blob([icalContent], { type: 'text/calendar;charset=utf-8' })
  const url = window.URL.createObjectURL(blob)
  
  const link = document.createElement('a')
  link.href = url
  link.download = filename
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
  
  window.URL.revokeObjectURL(url)
}
